name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22' # JDK version to make available on the path
        distribution: 'temurin' # Adoptium Temurin distribution

    - name: Build with Gradle
      run: ./gradlew